Fix  remember calls in k/js decoys (#815)
Such a snippet:

```kotlin
val a = remember { object {} }
```
used to break `compose:mpp:demo:jsRun` (it would break users apps too
when some new components are used)
```
java.lang.IllegalStateException: Not found Idx for androidx.compose.material3/ExposedDropdownMenuBox$composable|1568894224144511070[0]
```

this comitt fixes it.
____

This commit removes extra `copyWithNewTypeParams` for calls. It led to
new type generation for an anonymous object which didn't the type of
'val a'.

Note: Run all tests + tried some new cases, and tested with
compose:mpp:demo. This change didn't reveal any new issues. But there is
chance it can break something we don't know yet.


__
P.S. it's also fixed in the compiler plugin for 1.9.20-Beta -
https://github.com/JetBrains/compose-multiplatform-core/commits/release/compiler-integration-1.5.2.1

GitOrigin-RevId: 48ac2b85ec760ed7bc19fbb7a3c3d94f938358c4