Desktop: fix tests
We should always use TestComposeWindow/DesktopScreenshotTestRule/createComposeRule if we test compose classes.
Otherwise there will be an error sometimes:
      java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skija.Paint._nGetFinalizer()'

(because initCompose() may be not called before test)

Test: ./gradlew jvmTest desktopTest -Pandroidx.compose.multiplatformEnabled=true
Change-Id: I71ca818ebb892c81186b758e4d5286c7eb05c768


GitOrigin-RevId: b56ca32355c88bbfec7b9972c42d395769f7fc33