AndroidXDocsImplPlugin fix for configuration caching
Bug: 180423646

Test: enable configuration caching and run busytown/androidx.sh and see that it no longer emits this error:

  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':docs-tip-of-tree:unzipSampleSources'.
  Caused by: kotlin.UninitializedPropertyAccessException: lateinit property project has not been initialized
  	at androidx.build.docs.AndroidXDocsImplPlugin.getProject(AndroidXDocsImplPlugin.kt:71)
  	at androidx.build.docs.AndroidXDocsImplPlugin$configureUnzipTask$1$1.transform(AndroidXDocsImplPlugin.kt:166)
  	at androidx.build.docs.AndroidXDocsImplPlugin$configureUnzipTask$1$1.transform(AndroidXDocsImplPlugin.kt:164)

Change-Id: I8e55f866c8f2b7ced656c32b30eab658d9f33fc8


GitOrigin-RevId: a994c3eac6c95c3111b36e15b77f6d0c7593d9e9